Entirety of the Maflipulator Subsystem
chopshop-166/frc-2019 pull request #13
Opened 2019-02-09 18:31 UTC by DavidDesfosse

Has the maflipulator which differentiates between sides, restricts the movement so that it doesn't hit the lift, has PID, and is able to flip from one side of the robot to the other. Some minor changes to manipulator about the piston?

2019-02-09 18:54 UTC, msoucy requested changes

2019-02-09 18:54 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Maflipulator.java
> +        return new Command("move to position", this) {
Now that we have a working `Command`, refer to [the PIDCommand documentation](http://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/command/PIDCommand.html) and see if you can convert this to use `PIDCommand` instead.

2019-02-09 18:54 UTC, msoucy commented on src/main/java/frc/robot/maps/PracticeBot.java
> +                return new AnalogPotentiometer(8);
`return new MockPotentiometer();`, and fix the imports afterward

2019-02-09 20:19 UTC, bot190 requested changes

2019-02-09 20:19 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Maflipulator.java
> +                anglePID.setSetpoint(0);
Don't we need to be able to set the setpoint to a value, not just hardcode it to 0?

2019-02-09 20:19 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Maflipulator.java
> +    public Maflipulator(final RobotMap.MaflipulatorMap map) { // NOPMD
We need to figure out which side of the `lift` the `maflipulator` is on.

2019-02-14 01:30 UTC, msoucy commented
Closing this in favor of #12, which has been more recently updated.

David, collaborate with Quinlan to make changes as specified in #12 and push to his repository

2019-02-14 01:30 UTC, closed without merging